<a href="https://colab.research.google.com/github/matkeii/THC/blob/main/Clase_24_octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])
print(arr[0:4])
print(arr[1:6])
print(arr[1:])
print(arr[4:8])
print(arr[0:6])
print(arr[0:8])

[2 3 4 5]
[1 2 3 4]
[2 3 4 5 6]
[2 3 4 5 6 7]
[5 6 7]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7]


In [13]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


In [14]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [17]:
arr = np.array([1,2,3,4,5,6,7]) #EL ULTIMO ELEMENTO ES EL NEGATIVO

print(arr[-3:-1])
print(arr[-1])

[5 6]
7


In [18]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2]) #Primer numero: de donde parto---Segundo numero: donde quiero llegar---Tercer numero: pasos que quiero dar para ese numero

[2 4]


In [24]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[2:1])

[]


In [25]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4]) # VIAJA ENTRE RENGLONES::: 1 = 6,7,8,9,10 --- 1:4 = 0=6,1=7

[7 8 9]


In [32]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2, 2]) # VIAJA ENTRE COLUMNAS:::

[3 8]


In [35]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


In [39]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:1, 2:5])

[[3 4 5]]


In [42]:
arr = np.array([1,2,3,4,5,6,7])

filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


### ***Ejercicios de clase***

In [47]:
x = np.array([1,2,3])
y = np.array([4,5,6])

suma = x+y
print(f"La suma de los elementos es {suma.tolist()}") # F es contracción de forma

La suma de los elementos es [5, 7, 9]


In [49]:
x = np.array([1,2,3])
y = np.array([4,5,6])

resta = x-y
print(f"La resta de los elementos es {resta.tolist()}")

La resta de los elementos es [-3, -3, -3]


In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])

mult = x*y
print(f"La multiplicación es {mult.tolist()}")

La multiplicación es [4, 10, 18]


In [51]:
x = np.array([1,2,3])
y = np.array([4,5,6])

div = x/y
print(f"La división de los elementos es {div}")

La división de los elementos es [0.25 0.4  0.5 ]


In [52]:
print(f"El numero pi es: {np.pi}")

El numero pi es: 3.141592653589793


In [53]:
angulos = np.array([0,np.pi/2,np.pi])
seno = np.sin(angulos)

print(f"Los senos {seno}")
print(f"Los angulos {angulos}")

Los senos [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Los angulos [0.         1.57079633 3.14159265]


In [85]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
Pedir_num = input("Elija un numero del 1 al 10: ")

for x in range(0,10):
  num = np.random.randint(1,10, size=1)
  print(f"Su numero es: {num}?")


Elija un numero del 1 al 10: 5
Su numero es: [1]?
Su numero es: [7]?
Su numero es: [4]?
Su numero es: [7]?
Su numero es: [1]?
Su numero es: [3]?
Su numero es: [9]?
Su numero es: [6]?
Su numero es: [8]?
Su numero es: [7]?


### ***Continuación***

In [54]:
x = np.array(list(range(1,9))) # Para no declarar una lista por uno mismo

print(x)

[1 2 3 4 5 6 7 8]


In [58]:
matriz = x.reshape(4,2) # x = renglones(4) ---- y = columnas (2)
matriz

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
x.reshape(-1,1) #pasar un arreglo a matriz

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [60]:
x.reshape(-1,1).shape # nos dice que hay 8 renglones y una sola columna

(8, 1)

In [61]:
x = np.linspace(0,1,4) #USAMOS LINSPACE PARA CORTAR UNA RECTA DE NUMEROS EN CIERTOS PUNTOS el 4 es el numero de puntos que voy a hacer del 0 al 1
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [64]:
np.random.uniform(0,1,6)

array([0.02139719, 0.34235233, 0.24563432, 0.2341955 , 0.37412058,
       0.72937482])

In [65]:
np.random.randint(0,10,size=3) #Intervalo del 1 al 10 elige 3 numeros aleatorios

array([5, 0, 3])