<a href="https://colab.research.google.com/github/matkeii/THC/blob/main/Clase_19_Octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#arreglo bidimensional______ lista de listas____

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#arreglos tridimensionales _____lista de lista de listas______(matriz de matrices)
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim,a.shape) #0 listas
print(b.ndim,b.shape) #5 elementos en una lista
print(c.ndim,c.shape) #2 listas con 3 elementos cada una
print(d.ndim,d.shape) #2 listas que tienen dos listas dentro de ella y esas ultimas listas tienen 3 elementos

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [9]:
#entrar a cada elemento en arreglos

arr = np.array ([1,2,3,4,5])
print(arr[0]) #phyton empieza desde 0

1


In [51]:
#suma de elementos de una matriz (lista)
suma = 0
A = [[1,2,3], [4,5,6], [7,8,9]]
for i in range(len(A)):
  for j in range(len(A)):
    suma = suma+A[i][j]
print(suma)

45


In [48]:
#suma de elementos de una matriz (numpy)
import numpy as np
suma = 0
arr = np.array[[1,2,3], [4,5,6], [7,8,9]]
for i in range(len(A)):
  for j in range(len(A)):
    sumaArr = A[i][j] + suma
print(arr)

45


In [47]:
#producto escalar por renglones (numpy, listas)
suma = 0
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr1 = np.array([[10,11,12], [13,14,15], [16,17,18]])

C = len(arr) * [0]
print(C)
C0 = len(arr) * len(arr1)
print(arr[0][0])
print(arr1[0][0])

multiplicacion = arr[0][0] * arr1[0][0]
print(multiplicacion)



[0, 0, 0]
1
10
10


## ***EJERCICIOS RESUELTOS POR PROFESOR***

In [ ]:
#PRODUCTO PUNTO EN LISTAS
def ProdPunto(a,b):
  PP= 0
  for i in range (len(a)):
    PP=PP+a[i]*b[i]
  return PP

In [ ]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr3 = np.array([[10,11,12], [13,14,15], [16,17,18]])
Pp_por_renglones= np.array([0,0,0])
Pp_por_col = np.array([0,0,0])

In [ ]:
#producto punto por renglones

for i in range(len(arr2)):
  Pp_por_renglones[i]=ProdPunto(arr2[i],arr3[i])

Pp_por_renglones

In [61]:
def AC(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])

  return np.array(nuevo)

In [62]:
col1=AC(arr2,0)
col1

array([1, 4, 7])

In [ ]:
#Producto punto por columnas
for i in range(len(arr2)):
  Pp_por_col[i]=ProdPunto(AC)