<a href="https://colab.research.google.com/github/matkeii/THC/blob/main/TareaE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
C = np.zeros_like(arr1)

for i in range (len(arr1)):
  for j in range(len(arr1)):
    C[i][j] = (arr1[i][j] + arr2[i][j])

print("A=")
print(arr1[0:3, 0:3])
print("B=")
print(arr2[0:3, 0:3])
print(f"La suma de matrices es")
print(C)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
[[10 11 12]
 [13 14 15]
 [16 17 18]]
La suma de matrices es
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
C = np.zeros_like(arr1)

for i in range (len(arr1)):
  for j in range(len(arr1)):
    C[i][j] = (arr1[i][j] * arr2[i][j])

print("A=")
print(arr1[0:3, 0:3])
print("B=")
print(arr2[0:3, 0:3])
print(f"La multiplicación de matrices es")
print(C)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
[[10 11 12]
 [13 14 15]
 [16 17 18]]
La multiplicación de matrices es
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
traza = 0

for i in range(len(arr1)):
    traza += arr1[i][i]

print("A=")
print(arr1)
print(f"La traza de la matriz A es", traza)

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
La traza de la matriz es 15


***EJERCICIO 7, POTENCIA DE MATRICES***

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
